testName:
  long

server:
  host:
    localhost
  port:
    3000
db:
  user:
    root
  password:
    123456
  host: 
    localhost
  port: 
    3307
  dbName:
    my_go

redis:
  host:
    localhost
  port:
    6379
  password:
    123456
  db:
    0